# Название нашего рабочего процесса.
name: Java CI with Gradle

# Триггер: Указываем, когда запускать этот процесс.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Задачи: Описываем работу, которую нужно выполнить.
jobs:
  build:
    # Указываем, на какой виртуальной машине ее выполнять.
    runs-on: ubuntu-latest

    # Шаги: Последовательность команд, которые нужно выполнить.
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Настройка Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # <-- НАШ НОВЫЙ ШАГ -->
      # Шаг 3: Установка Google Chrome
      # Используем готовое действие, которое само скачает и установит последнюю
      # стабильную версию браузера на виртуальную машину.
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      # Шаг 4: Делаем gradlew исполняемым
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Шаг 5: Запуск тестов
      - name: Run tests with Gradle
        run: ./gradlew clean test --no-daemon

      # Шаг 6 (Бонус): Выгрузка Allure-отчета
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results
          retention-days: 7